#!/data/data/com.termux/files/usr/bin/bash

function log_status() {
  if [ "$1" -eq 0 ]; then
    echo "LAMP up: service ${2} started successfully"
  else
    echo "LAMP up: something went wrong with ${2}!"
  fi
}

sv up mysqld &
status="$?"
sleep 5
log_status $status mysqld

sv up php-fpm &
status="$?"
sleep 2
log_status $status php-fpm

apachectl -k start
status="$?"
sleep 2
log_status $status apache2
